# Generated by Django 5.0.4 on 2024-04-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_juego_fecha_juego_hora_fin_juego_hora_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistema',
            old_name='descrpcion',
            new_name='descripcion',
        ),
    ]
